### ISSUE TITLE
Premailing Checklist

### ISSUE THREAD

**Issue by dsunder** [kokkos/array_ref#47]
- [ ] Update P0019 to reflex Albuquerque notes
- [ ] Create new paper to discuss property ontology
- [ ] Update P0546 to reference property ontology
- [ ] Update P0860 to reference property ontology
- [ ] Update P0856 to reference property ontology
- [ ] Update P0009 to reflex Albuquerque meeting notes
- [ ] Review P00332 for strength and clarity
- [ ] Proofread for grammar and wording

**Comment by dhollman** [comment]
FYI, property ontology paper is P0900

**Comment by hcedwar** [comment]
@dhollman Where is the ontology paper draft to reference from the other papers?

**Comment by dhollman** [comment]
Sorry, didn't realize I haven't put in the pull request. Should be there now

**Comment by dhollman** [comment]
@hcedwar I'm done with the draft versions of P0900 and P0856. Let me know when you've gotten a chance to read-through them so I can do one more read-through myself.

**Comment by dhollman** [comment]
FYI, in P0900 I decided to stick with "property" and "property mode" rather than switching to "property-type" and "property-value".  I don't care about the naming that much, but most of the paper was already written that way so I didn't bother changing it.
